### PR TITLE
fix: filter unsupported Anthropic-Beta headers from Bedrock

### LINKED ISSUE #221: bug: `Anthropic-Beta` header forwarded to Bedrock causes `invalid beta flag` errors
## Summary

When routing requests through Bedrock, AI Bridge forwards the `Anthropic-Beta` header from the client unchanged. Claude Code sends beta flags like `adaptive-thinking-2026-01-28` that are not recognized by all Bedrock regions/models (particularly GovCloud `us-gov-west-1`), causing 400 errors:

```
API Error: 400 {"error":{"message":"POST \"https://bedrock-runtime.us-gov-west-1.amazonaws.com/v1/messages\": 400 Bad Request {\"message\":\"invalid beta flag\"}","type":"api_error"},"request_id":"","type":"error"}
```

## Root Cause

The `Anthropic-Beta` header is listed in `anthropicForwardHeaders` in `provider/anthropic.go` and forwarded via `BuildUpstreamHeaders()` in `intercept/client_headers.go`. This works fine for the direct Anthropic API, but Bedrock has its own feature gating and does not accept all Anthropic beta flags.

Claude Code sends beta values like:

```
claude-code-20250219,adaptive-thinking-2026-01-28,context-management-2025-06-27,prompt-caching-scope-2026-01-05,effort-2025-11-24
```

Some of these flags are not supported on older Bedrock regions/models.

## Expected Behavior

When routing through Bedrock, the `Anthropic-Beta` header should either be:

* Stripped entirely (the Bedrock SDK/API handles feature gating differently), or
* Filtered to only include flags known to be supported by Bedrock

## Impact

This blocks usage of Claude Code through AI Bridge with Bedrock in GovCloud regions. The `CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING=1` workaround for [AIGOV-103](https://linear.app/codercom/issue/AIGOV-103/bug-bedrock-models-that-dont-support-adaptive-thinking-reject) does not help because it only changes the request body — Claude Code still sends the unsupported beta header.

## Prior Art

LiteLLM encountered the same issue and solved it by maintaining a provider-specific beta header allowlist: [https://docs.litellm.ai/blog/claude-code-beta-headers-incident](<https://docs.litellm.ai/blog/claude-code-beta-headers-incident>)

## References

* Related: [AIGOV-103](https://linear.app/codercom/issue/AIGOV-103/bug-bedrock-models-that-dont-support-adaptive-thinking-reject)
* `anthropicForwardHeaders` in `provider/anthropic.go`
* `BuildUpstreamHeaders()` in `intercept/client_headers.go`
* LiteLLM incident: [https://docs.litellm.ai/blog/claude-code-beta-headers-incident](<https://docs.litellm.ai/blog/claude-code-beta-headers-incident>)
* Claude Code issue: [https://github.com/anthropics/claude-code/issues/11672](<https://github.com/anthropics/claude-code/issues/11672>)

---

Created on behalf of @uzair-coder07

### PR DESCRIPTION
**Pull request by pawbana**
Removes headers from requests to Bedrock that are unsupported.

Fixes: https://github.com/coder/aibridge/issues/221

### CODE REVIEW

**Comment by pawbana** [comment]
* **#226** <a href="https://app.graphite.com/github/pr/coder/aibridge/226?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/coder/aibridge/226?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#225** <a href="https://app.graphite.com/github/pr/coder/aibridge/225?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#218** <a href="https://app.graphite.com/github/pr/coder/aibridge/218?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#215** <a href="https://app.graphite.com/github/pr/coder/aibridge/215?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#213** <a href="https://app.graphite.com/github/pr/coder/aibridge/213?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: intercept/messages/base.go [hunk 1]
```diff
@@ -32,6 +32,23 @@ import (
 	"cdr.dev/slog/v3"
 )
 
+// bedrockSupportedBetaFlags is the set of Anthropic-Beta flags that AWS Bedrock
+// accepts. Flags not in this set cause a 400 "invalid beta flag" error.
+//
+// https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages-request-response.html
+var bedrockSupportedBetaFlags = map[string]bool{
```
Comment (dannykopping) [inline intercept/messages/base.go:40]: _Aside:_

We can't move to the blind reverse-proxy approach soon enough; this is going to be a nightmare to maintain, with lots of silent issues :sweat:

File: intercept/messages/reqpayload.go [hunk 2]
```diff
@@ -342,17 +351,35 @@ func (p MessagesRequestPayload) convertAdaptiveThinkingForBedrock() (MessagesReq
...
 			return p, fmt.Errorf("removing %q: %w", field, err)
 		}
 	}
+
+	// Strip beta-gated fields only when their beta flag is missing.
+	betaHeader := headers.Get("Anthropic-Beta")
+	for field, requiredFlag := range bedrockBetaGatedFields {
+		if !strings.Contains(betaHeader, requiredFlag) {
+			var err error
+			result, err = result.delete(field)
```
Comment (dannykopping) [inline intercept/messages/reqpayload.go]: Same comment as downstack; this parsed the JSON for each field which is inefficient.

File: intercept/messages/reqpayload.go [hunk 3]
```diff
@@ -62,12 +64,19 @@ var (
...
 		messagesReqPathServiceTier,
 		messagesReqPathContainer,
 		messagesReqPathInferenceGeo,
-		messagesReqPathContextManagement,
+	}
+
+	// bedrockBetaGatedFields maps body fields to the beta flag that enables them.
+	// If the beta flag is present in the (already-filtered) Anthropic-Beta header,
+	// the field is kept; otherwise it is stripped. Model-specific beta flags must
+	// be removed from the header before this check (see filterModelGatedBetaFlags).
```
Comment (dannykopping) [inline intercept/messages/reqpayload.go]: This should be `filterBedrockBetaFlags`, no?

File: intercept/messages/base_test.go [hunk 4]
```diff
@@ -615,70 +617,111 @@ func TestAugmentRequestForBedrock_AdaptiveThinking(t *testing.T) {
...
+			expectBudgetTokens:  2000, // 10000 * 0.2 (low effort)
+			expectRemovedFields: []string{"output_config"},
 		},
 		{
-			name:               "4_6_model_with_output_config_strips_it",
-			bedrockModel:       "anthropic.claude-opus-4-6-v1",
-			requestBody:        `{"model":"claude-opus-4-6","max_tokens":10000,"thinking":{"type":"adaptive"},"output_config":{"effort":"high"},"messages":[]}`,
-			expectThinkingType: "adaptive",
-			expectBudgetTokens: 0,
+			name:             "output_config_kept_when_effort_beta_flag_present_on_opus_4_5",
```
Comment (dannykopping) [inline intercept/messages/base_test.go:656]: Does this actually check if `output_config` is kept?

File: intercept/messages/base_test.go [hunk 5]
```diff
@@ -615,70 +617,111 @@ func TestAugmentRequestForBedrock_AdaptiveThinking(t *testing.T) {
...
-			expectBudgetTokens: 0,
+			name:                "output_config_stripped_for_non_opus_4_5_even_with_effort_beta_flag",
+			bedrockModel:        "anthropic.claude-sonnet-4-5-20250929-v1:0",
+			clientBetaFlags:     "effort-2025-11-24,interleaved-thinking-2025-05-14",
+			requestBody:         `{"model":"claude-sonnet-4-5","max_tokens":10000,"messages":[],"output_config":{"effort":"high"}}`,
+			expectRemovedFields: []string{"output_config"},
+			expectBetaHeader:    "interleaved-thinking-2025-05-14",
+		},
+		{
+			name:             "context_management_kept_when_beta_flag_present",
```
Comment (dannykopping) [inline intercept/messages/base_test.go:672]: Same issue; what's ensuring this is kept?

File: intercept/messages/base_test.go (hunk 4 above)
Comment (dannykopping) [reply intercept/messages/base_test.go:656]: @pawbana did you miss this?

**Review by dannykopping — APPROVED** [review]
LGTM

File: intercept/messages/base_test.go (hunk 4 above)
Comment (pawbana) [reply intercept/messages/base_test.go:656]: Sorry, added check if fields are kept.

**Comment by pawbana** [comment]
### Merge activity

* **Mar 26, 4:28 PM UTC**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.com/github/pr/coder/aibridge/226).
* **Mar 26, 4:35 PM UTC**: [Graphite](https://app.graphite.com/github/pr/coder/aibridge/226) rebased this pull request as part of a merge.
* **Mar 26, 4:38 PM UTC**: @pawbana merged this pull request with [Graphite](https://app.graphite.com/github/pr/coder/aibridge/226).
